# Generated by Django 6.0.7 on 2026-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
