# Generated by Django 6.0.7 on 2026-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "В процессе оплаты"), ("paid", "Оплачено")],
                default="unpaid",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
    ]
