name: Django CI/CD Pipeline

on:
  push:
    branches: [ "docker-homework", "main", "master" ]
  pull_request:
    branches: [ "docker-homework", "main", "master" ]

jobs:
  #ЭТАП 1: ТЕСТЫ, ФОРМАТИРОВАНИЕ И ЛИНТЕР
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Устанавливаем необходимые утилиты для проверок
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black

      # Проверяем форматирование кода (Black)
      - name: Check code formatting with Black
        run: |
          black --check .

      # Запускаем линтер синтаксиса (Flake8)
      - name: Run Linter (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Прогоняем юнит-тесты Django
      - name: Run Django tests
        run: |
          python manage.py test

  #ЭТАП 2: ДЕПЛОЙ И СБОРКА НА СЕРВЕРЕ ПО SSH
  deploy:
    runs-on: ubuntu-latest
    needs: tests # Запускается только при успешных тестах

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Копируем ВСЕ файлы проекта (включая docker-compose.yaml) на сервер в Яндексе
      - name: Copy files via SSH (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          target: "/home/skypro/lms_project"

      # Заходим по SSH и запускаем Docker Compose
      - name: Run Docker Compose on Remote Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Переходим в рабочую папку проекта
            cd /home/skypro/lms_project
            
            # Подкладываем сохраненный файл секретов .env из домашней директории
            cp ~/.env .env
            
            # Собираем и запускаем контейнеры с явным указанием файла .yaml
            sudo docker compose -f docker-compose.yaml up -d --build --remove-orphans
            
            # Чистим старые кэшированные образы
            sudo docker image prune -f
